### ISSUE TITLE
Reworked version of "why should you join SurPathHub" section

### ISSUE THREAD

**Issue by Ryjin210** [SurPathHub/content-writing#8]
![WSYJ](https://user-images.githubusercontent.com/77573336/137275277-1a5c0871-56a3-47a0-9653-58b13764c418.jpg)

**Comment by vinzvinci** [comment]
Thanks, I love that :) that's so much value for me

**Comment by Ryjin210** [comment]
> Thanks, I love that :) that's so much value for me

Okay i'll go pull up a request now, thanks
